name: KnockbackFFA
version: '${project.version}'
main: me.gameisntover.knockbackffa.KnockbackFFALegacy
authors: [ GaMeIsNtOvEr ]
softdepend:
  - 'PlaceholderAPI'
description: Knockback ffa is a gamemode which gives every players knockback stick and some other stuffs which makes the game more fun!
